apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rest
      port: {{ .Values.elasticsearch.containerPort | 9200 }}
      targetPort: {{ .Values.elasticsearch.containerPort | 9200 }}
    - name: inter-node
      port: 9300
      targetPort: 9300
  selector:
    {{- include "efk-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch