apiVersion: apps/v1
kind: StatefulSet
metadata:
  # Use the fullname helper for consistent naming
  name: {{ include "efk-stack.fullname" . }}-es-cluster
  namespace: {{ .Release.Namespace }}
  # Use the labels helper to apply standard labels
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  serviceName: "elasticsearch" # This is linked to the Headless Service
  selector:
    # This selector must match the labels on the pod template
    matchLabels:
      {{- include "efk-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: elasticsearch
  template:
    metadata:
      labels:
        # These labels are applied to the pods
        {{- include "efk-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: elasticsearch
    spec:
      # This is the modern, secure way to handle volume permissions.
      # It replaces the need for a privileged 'fix-permissions' init container.
      securityContext:
        fsGroup: 1000
      
      # These init containers are still useful but can be disabled in values.yaml
      # if your Kubernetes nodes are already configured with these settings.
      {{- if .Values.elasticsearch.initContainers.enabled }}
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
            runAsUser: 0
        - name: increase-fd-ulimit
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      {{- end }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          env:
            - name: cluster.name
              value: {{ .Values.elasticsearch.clusterName | quote }}
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # These values are now dynamically generated by the helpers in _helpers.tpl
            - name: discovery.seed_hosts
              value: {{ include "elasticsearch.discoveryHosts" . | quote }}
            - name: cluster.initial_master_nodes
              value: {{ include "elasticsearch.masterNodes" . | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts | quote }}
          ports:
            - name: rest
              containerPort: {{ .Values.elasticsearch.containerPort | 9200 }}
            - name: inter-node
              containerPort: 9300
          resources:
            # Resource requests/limits are now configurable
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        # Allow storage class to be specified in values.yaml
        {{- if .Values.elasticsearch.storage.storageClassName }}
        storageClassName: {{ .Values.elasticsearch.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage.size | quote }}