apiVersion: apps/v1
kind: DaemonSet
metadata:
  # Use the fullname helper from _helpers.tpl for consistent naming
  name: {{ include "efk-stack.fullname" . }}-fluentd
  namespace: {{ .Release.Namespace }}
  # Use the labels helper to apply standard labels
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
spec:
  selector:
    # The selector must match the labels on the pod template
    matchLabels:
      {{- include "efk-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fluentd
  template:
    metadata:
      labels:
        # These labels are applied to the pods
        {{- include "efk-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fluentd
    spec:
      serviceAccountName: fluentd # Assuming a fluentd service account exists
      tolerations:
        # This makes the tolerations configurable from values.yaml
        {{- toYaml .Values.fluentd.tolerations | nindent 8 }}
      containers:
        - name: fluentd
          image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          env:
            # These values now come from your values.yaml for easy configuration
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.fluentd.elasticsearch.host | quote }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.fluentd.elasticsearch.port | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.fluentd.elasticsearch.scheme | quote }}
            - name: FLUENTD_SYSTEMD_CONF
              value: {{ .Values.fluentd.systemdConf | quote }}

            # --- Secure Credential Handling ---
            # User is not a secret, can be set directly from values
            - name: FLUENT_ELASTICSEARCH_USER
              value: {{ .Values.fluentd.elasticsearch.user | quote }}
            # Password comes securely from a Kubernetes Secret
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fluentd.elasticsearch.existingSecret | default (printf "%s-credentials" .Values.fluentd.elasticsearch.host) }}
                  key: password
          resources:
            # Resource requests/limits are now configurable
            {{- toYaml .Values.fluentd.resources | nindent 12 }}
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: fluentd-config
          configMap:
            # Ensure the ConfigMap name matches the one you created
            name: {{ include "efk-stack.fullname" . }}-fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers